from abc import ABC, abstractmethod
from pathlib import Path


class ProviderBase(ABC):
    @abstractmethod
    async def send_report(
        self,
        to_email: str,
        from_email: str,
        company_name: str,
        pdf_path: Path,
        docx_path: Path | None = None,
    ) -> bool: ...

    def _build_html_body(self, company_name: str) -> str:
        return f"""
        <html>
        <body style="font-family: Arial, sans-serif; color: #333;">
            <div style="max-width: 600px; margin: 0 auto; padding: 24px;">
                <h1 style="color: #1a237e;">Business Intelligence Report</h1>
                <p>Your report for <strong>{company_name}</strong> is ready.</p>
                <p>The attached report includes:</p>
                <ul>
                    <li>Executive Summary</li>
                    <li>Business Profile</li>
                    <li>Market Analysis</li>
                    <li>Competitive Analysis</li>
                    <li>SWOT Analysis</li>
                    <li>Recommendations & Risk Factors</li>
                </ul>
                <hr style="border: none; border-top: 1px solid #ddd; margin: 24px 0;">
                <p style="color: #888; font-size: 12px;">
                    Generated by Business Intelligence System
                </p>
            </div>
        </body>
        </html>
        """
